"""The Render blueprint must not deploy a configuration that quietly misbehaves.

`render.yaml` is never executed by the test suite and never runs locally, so
nothing else in this repository would notice if it drifted. Two of these checks
exist because the blueprint really did carry the wrong value: it set
RS_MODEL_PROVIDER=development, which would have graded real retinal images with
the placeholder stub from the first day of a deployment.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
BLUEPRINT = REPO_ROOT / "render.yaml"


@pytest.fixture(scope="module")
def blueprint() -> dict:
    assert BLUEPRINT.is_file(), f"{BLUEPRINT} is missing"
    return yaml.safe_load(BLUEPRINT.read_text(encoding="utf-8"))


def env_of(service: dict) -> dict[str, dict]:
    return {entry["key"]: entry for entry in service.get("envVars", [])}


def backend_services(blueprint: dict) -> list[dict]:
    """Services that run application code (the static site has no RS_ config)."""
    return [s for s in blueprint["services"] if s.get("runtime") == "python"]


def test_blueprint_parses(blueprint: dict) -> None:
    assert blueprint["services"], "no services declared"
    assert blueprint["databases"], "no database declared"


def test_no_service_serves_the_placeholder_model(blueprint: dict) -> None:
    """The stub is honest about being a stub, but it must never reach production.

    ModelRegistry.resolve() reads the database first and falls back to these
    variables when nothing is registered — which is exactly the state of a
    freshly provisioned database.
    """
    for service in backend_services(blueprint):
        provider = env_of(service).get("RS_MODEL_PROVIDER", {}).get("value")
        assert provider == "onnx", (
            f"{service['name']} sets RS_MODEL_PROVIDER={provider!r}; a fresh "
            "deployment would grade real images with the development stub"
        )


def test_model_version_matches_a_committed_artefact(blueprint: dict) -> None:
    """The settings fallback loads `{model_dir}/{version}.onnx` — by FILENAME.

    Using the registry version ("v2") instead of the filename ("dr-v2") yields
    a provider that reports itself unavailable, which is a silent outage.
    """
    for service in backend_services(blueprint):
        version = env_of(service).get("RS_ACTIVE_MODEL_VERSION", {}).get("value")
        assert version, f"{service['name']} does not pin RS_ACTIVE_MODEL_VERSION"
        artefact = REPO_ROOT / "ml" / "models" / f"{version}.onnx"
        assert artefact.is_file(), (
            f"{service['name']} points at {version}.onnx, which is not committed. "
            f"Expected {artefact}"
        )


def test_api_and_worker_agree_on_the_model(blueprint: dict) -> None:
    """A worker grading with a different model than the API reports is invisible."""
    settings = {
        service["name"]: (
            env_of(service).get("RS_MODEL_PROVIDER", {}).get("value"),
            env_of(service).get("RS_ACTIVE_MODEL_VERSION", {}).get("value"),
        )
        for service in backend_services(blueprint)
    }
    assert len(set(settings.values())) == 1, f"model configuration diverges: {settings}"


def test_production_never_uses_filesystem_storage(blueprint: dict) -> None:
    """A container disk is ephemeral; retinal images would vanish on deploy."""
    for service in backend_services(blueprint):
        provider = env_of(service).get("RS_STORAGE_PROVIDER", {}).get("value")
        assert provider == "s3", (
            f"{service['name']} sets RS_STORAGE_PROVIDER={provider!r}"
        )


def test_no_secret_is_committed_in_the_blueprint(blueprint: dict) -> None:
    """Secrets must be generated by Render or set in its dashboard, never here."""
    secret_keys = {
        "RS_JWT_SECRET",
        "RS_JWT_REFRESH_SECRET",
        "RS_STORAGE_SIGNING_SECRET",
        "RS_S3_ACCESS_KEY_ID",
        "RS_S3_SECRET_ACCESS_KEY",
        "RS_SEED_ADMIN_PASSWORD",
        "RS_DATABASE_URL",
    }
    for service in blueprint["services"]:
        for key, entry in env_of(service).items():
            if key in secret_keys:
                assert "value" not in entry, (
                    f"{service['name']} commits a literal value for {key}"
                )


def test_every_service_declares_production(blueprint: dict) -> None:
    """RS_ENV drives the guards that refuse placeholder secrets and local storage."""
    for service in backend_services(blueprint):
        assert env_of(service).get("RS_ENV", {}).get("value") == "production", (
            f"{service['name']} does not declare RS_ENV=production"
        )
