"""Development model provider — **NOT A SCREENING MODEL**.

This backend exists so the full pipeline (capture -> quality -> inference ->
explanation -> risk -> referral -> review) can be built, tested and demonstrated
before a trained model exists.

It does **not** detect diabetic retinopathy. Its output is a deterministic
function of image content — stable across runs so tests and demos are
reproducible — and carries no clinical meaning whatsoever. Every result is
flagged ``is_development_model=True`` and carries an explicit warning, which the
API and every UI surface must display.

No accuracy, sensitivity, specificity or any other performance claim may be
attached to this provider, because none has been measured.
"""

from __future__ import annotations

import hashlib
import time

import numpy as np

from app.ml.providers.base import ModelProvider, PredictionOutput, softmax
from app.domain.enums import ScreeningCategory

DEVELOPMENT_WARNING = (
    "DEVELOPMENT MODEL — NOT FOR CLINICAL USE. This output is generated by a "
    "placeholder and has no diagnostic meaning."
)


class DevelopmentModelProvider(ModelProvider):
    def __init__(self, *, version: str = "dev-0.0.0", input_size: tuple[int, int] = (224, 224)):
        self._version = version
        self._input_size = input_size

    @property
    def model_version(self) -> str:
        return self._version

    @property
    def framework(self) -> str:
        return "development"

    @property
    def is_development_model(self) -> bool:
        return True

    @property
    def input_size(self) -> tuple[int, int]:
        return self._input_size

    def is_available(self) -> bool:
        return True

    def supports_gradcam(self) -> bool:
        # A synthetic saliency map is produced so the explanation UI can be
        # built and reviewed; it is not a real attribution map.
        return True

    def predict(self, tensor: np.ndarray) -> PredictionOutput:
        started = time.perf_counter()

        # Deterministic seed from image content: identical input -> identical
        # output, so demos and tests are reproducible.
        digest = hashlib.sha256(np.ascontiguousarray(tensor).tobytes()).digest()
        seed = int.from_bytes(digest[:8], "big") % (2**32)
        rng = np.random.default_rng(seed)

        logits = rng.normal(loc=0.0, scale=1.5, size=len(self.classes)).astype(np.float32)
        probabilities = softmax(logits)

        index = int(np.argmax(probabilities))
        category = ScreeningCategory(self.classes[index])
        duration_ms = int((time.perf_counter() - started) * 1000)

        # A coarse activation grid, derived from the input's own luminance, so
        # the Grad-CAM overlay has something structurally plausible to render.
        activations = self._pseudo_activations(tensor, rng)

        return PredictionOutput(
            category=category,
            confidence=float(probabilities[index]),
            probabilities={
                name: float(value) for name, value in zip(self.classes, probabilities)
            },
            model_version=self.model_version,
            framework=self.framework,
            is_development_model=True,
            duration_ms=duration_ms,
            activations=activations,
            warnings=[DEVELOPMENT_WARNING],
        )

    def _pseudo_activations(self, tensor: np.ndarray, rng: np.random.Generator) -> np.ndarray:
        """A 7x7 map loosely following image brightness. Not an attribution."""
        image = tensor[0].mean(axis=0)  # (H, W)
        grid = 7
        height, width = image.shape
        cell_h, cell_w = max(1, height // grid), max(1, width // grid)
        pooled = np.zeros((grid, grid), dtype=np.float32)
        for row in range(grid):
            for col in range(grid):
                block = image[
                    row * cell_h : (row + 1) * cell_h, col * cell_w : (col + 1) * cell_w
                ]
                pooled[row, col] = float(block.mean()) if block.size else 0.0

        pooled += rng.normal(0.0, 0.05, pooled.shape).astype(np.float32)
        spread = float(pooled.max() - pooled.min()) or 1.0
        return (pooled - pooled.min()) / spread


class UnavailableModelProvider(ModelProvider):
    """Stands in when a real model is configured but cannot be loaded.

    It never fabricates a prediction — calling :meth:`predict` raises, so a
    missing model surfaces as an honest error rather than a silent downgrade to
    placeholder output.
    """

    def __init__(self, *, reason: str, version: str = "unavailable") -> None:
        self.reason = reason
        self._version = version

    @property
    def model_version(self) -> str:
        return self._version

    @property
    def framework(self) -> str:
        return "unavailable"

    @property
    def is_development_model(self) -> bool:
        return False

    @property
    def input_size(self) -> tuple[int, int]:
        return (224, 224)

    def is_available(self) -> bool:
        return False

    def predict(self, tensor: np.ndarray) -> PredictionOutput:
        from app.ml.providers.base import ModelNotAvailableError

        raise ModelNotAvailableError(f"MODEL NOT AVAILABLE — {self.reason}")
