"""Add patient medical history and prescriptions

Revision ID: 1bb1c3149dce
Revises: 82ea3a725441
Created: 2026-09-03 13:02:47.119409
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1bb1c3149dce'
down_revision: str | None = '82ea3a725441'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_history_entries',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_history_entries_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_patient_history_entries_recorded_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_patient_history_entries_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_history_entries'))
    )
    with op.batch_alter_table('patient_history_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_history_entries_entry_type'), ['entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_history_entries_is_removed'), ['is_removed'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_history_entries_patient_id'), ['patient_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('prescribed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_prescriptions_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescribed_by_user_id'], ['users.id'], name=op.f('fk_prescriptions_prescribed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], name=op.f('fk_prescriptions_session_id_screening_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions'))
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_prescribed_by_user_id'), ['prescribed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescriptions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_status'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_session_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_prescribed_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_prescriptions_patient_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('patient_history_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_history_entries_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_history_entries_is_removed'))
        batch_op.drop_index(batch_op.f('ix_patient_history_entries_entry_type'))

    op.drop_table('patient_history_entries')
    # ### end Alembic commands ###
