"""initial schema

Revision ID: 82ea3a725441
Revises: 
Created: 2026-08-22 23:46:57.807943
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '82ea3a725441'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('connectivity_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinics'))
    )
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinics_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_clinics_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinics_status'), ['status'], unique=False)

    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('roles',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_role'), ['actor_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_result'), ['result'], unique=False)

    op.create_table('doctors',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('specialty', sa.String(length=128), nullable=False),
    sa.Column('license_number', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_doctors_clinic_id_clinics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_doctors_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctors'))
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_user_id'), ['user_id'], unique=True)

    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('rollout_notes', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_feature_flags_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags'))
    )
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_flags_key'), ['key'], unique=True)

    op.create_table('health_workers',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('staff_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_health_workers_clinic_id_clinics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_health_workers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_workers'))
    )
    with op.batch_alter_table('health_workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_workers_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_workers_user_id'), ['user_id'], unique=True)

    op.create_table('model_metadata',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('deployment_target', sa.String(length=32), nullable=False),
    sa.Column('architecture', sa.String(length=64), nullable=True),
    sa.Column('input_width', sa.Integer(), nullable=False),
    sa.Column('input_height', sa.Integer(), nullable=False),
    sa.Column('classes', sa.JSON(), nullable=False),
    sa.Column('model_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_metrics', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('registered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['users.id'], name=op.f('fk_model_metadata_registered_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_metadata')),
    sa.UniqueConstraint('name', 'version', name=op.f('uq_model_metadata_name'))
    )
    with op.batch_alter_table('model_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_metadata_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_metadata_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_metadata_validation_status'), ['validation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_metadata_version'), ['version'], unique=False)

    op.create_table('patients',
    sa.Column('patient_code', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('has_diabetes', sa.Boolean(), nullable=True),
    sa.Column('diabetes_duration_years', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('registered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('portal_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_patients_clinic_id_clinics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portal_user_id'], ['users.id'], name=op.f('fk_patients_portal_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registered_by_user_id'], ['users.id'], name=op.f('fk_patients_registered_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_patient_code'), ['patient_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_portal_user_id'), ['portal_user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name=op.f('uq_role_permissions_role_id'))
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('sync_queue',
    sa.Column('local_id', sa.String(length=64), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], name=op.f('fk_sync_queue_submitted_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_queue')),
    sa.UniqueConstraint('local_id', 'entity_type', name=op.f('uq_sync_queue_local_id'))
    )
    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_queue_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_queue_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_queue_local_id'), ['local_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_queue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_queue_submitted_by_user_id'), ['submitted_by_user_id'], unique=False)

    op.create_table('system_configuration',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_system_configuration_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_configuration'))
    )
    with op.batch_alter_table('system_configuration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_configuration_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_configuration_key'), ['key'], unique=True)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name=op.f('uq_user_roles_user_id'))
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('patient_consents',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('consent_type', sa.String(length=32), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_consents_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('fk_patient_consents_recorded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_consents'))
    )
    with op.batch_alter_table('patient_consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_consents_consent_type'), ['consent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_consents_patient_id'), ['patient_id'], unique=False)

    op.create_table('screening_sessions',
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=True),
    sa.Column('conducted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.String(length=255), nullable=True),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('captured_offline', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('fk_screening_sessions_clinic_id_clinics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conducted_by_user_id'], ['users.id'], name=op.f('fk_screening_sessions_conducted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_screening_sessions_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screening_sessions'))
    )
    with op.batch_alter_table('screening_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screening_sessions_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_sessions_conducted_by_user_id'), ['conducted_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_sessions_local_id'), ['local_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_screening_sessions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_sessions_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_sessions_sync_status'), ['sync_status'], unique=False)

    op.create_table('retinal_images',
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('eye_side', sa.String(length=8), nullable=False),
    sa.Column('capture_index', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_retinal_images_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], name=op.f('fk_retinal_images_session_id_screening_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retinal_images')),
    sa.UniqueConstraint('session_id', 'eye_side', 'capture_index', name=op.f('uq_retinal_images_session_id'))
    )
    with op.batch_alter_table('retinal_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retinal_images_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_retinal_images_eye_side'), ['eye_side'], unique=False)
        batch_op.create_index(batch_op.f('ix_retinal_images_local_id'), ['local_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_retinal_images_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retinal_images_session_id'), ['session_id'], unique=False)

    op.create_table('inference_results',
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('eye_side', sa.String(length=8), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('class_probabilities', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('inference_mode', sa.String(length=24), nullable=True),
    sa.Column('is_development_model', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['retinal_images.id'], name=op.f('fk_inference_results_image_id_retinal_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['model_metadata.id'], name=op.f('fk_inference_results_model_id_model_metadata'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], name=op.f('fk_inference_results_session_id_screening_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inference_results'))
    )
    with op.batch_alter_table('inference_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inference_results_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_results_image_id'), ['image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_results_is_development_model'), ['is_development_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_results_local_id'), ['local_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inference_results_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inference_results_status'), ['status'], unique=False)

    op.create_table('quality_assessments',
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('is_acceptable', sa.Boolean(), nullable=False),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('blur_score', sa.Float(), nullable=False),
    sa.Column('lighting_score', sa.Float(), nullable=False),
    sa.Column('framing_score', sa.Float(), nullable=False),
    sa.Column('retinal_visibility_score', sa.Float(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('thresholds_snapshot', sa.JSON(), nullable=False),
    sa.Column('assessed_on_device', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['retinal_images.id'], name=op.f('fk_quality_assessments_image_id_retinal_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], name=op.f('fk_quality_assessments_session_id_screening_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_assessments'))
    )
    with op.batch_alter_table('quality_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_assessments_image_id'), ['image_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_quality_assessments_is_acceptable'), ['is_acceptable'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_assessments_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_assessments_session_id'), ['session_id'], unique=False)

    op.create_table('explanations',
    sa.Column('inference_result_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('heatmap_storage_key', sa.String(length=512), nullable=True),
    sa.Column('overlay_storage_key', sa.String(length=512), nullable=True),
    sa.Column('affected_regions', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('is_development_model', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inference_result_id'], ['inference_results.id'], name=op.f('fk_explanations_inference_result_id_inference_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], name=op.f('fk_explanations_session_id_screening_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_explanations'))
    )
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_explanations_inference_result_id'), ['inference_result_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_explanations_session_id'), ['session_id'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('inference_result_id', sa.Uuid(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('recommended_action', sa.String(length=255), nullable=False),
    sa.Column('requires_clinician_review', sa.Boolean(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('rules_snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inference_result_id'], ['inference_results.id'], name=op.f('fk_risk_assessments_inference_result_id_inference_results'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], name=op.f('fk_risk_assessments_session_id_screening_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessments'))
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_requires_clinician_review'), ['requires_clinician_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_session_id'), ['session_id'], unique=False)

    op.create_table('referrals',
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('risk_assessment_id', sa.Uuid(), nullable=True),
    sa.Column('to_clinic_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_doctor_id', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_doctor_id'], ['doctors.id'], name=op.f('fk_referrals_assigned_doctor_id_doctors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_referrals_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_referrals_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], name=op.f('fk_referrals_risk_assessment_id_risk_assessments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], name=op.f('fk_referrals_session_id_screening_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_clinic_id'], ['clinics.id'], name=op.f('fk_referrals_to_clinic_id_clinics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals'))
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_assigned_doctor_id'), ['assigned_doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_local_id'), ['local_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_referrals_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_referrals_to_clinic_id'), ['to_clinic_id'], unique=False)

    op.create_table('clinical_reviews',
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('referral_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('clinician_category', sa.String(length=24), nullable=True),
    sa.Column('agrees_with_ai', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_clinical_reviews_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_clinical_reviews_referral_id_referrals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], name=op.f('fk_clinical_reviews_reviewer_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], name=op.f('fk_clinical_reviews_session_id_screening_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_reviews'))
    )
    with op.batch_alter_table('clinical_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_reviews_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_reviews_local_id'), ['local_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_clinical_reviews_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_reviews_reviewer_user_id'), ['reviewer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_reviews_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_reviews_status'), ['status'], unique=False)

    op.create_table('follow_ups',
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('review_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_follow_ups_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_follow_ups_patient_id_patients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['clinical_reviews.id'], name=op.f('fk_follow_ups_review_id_clinical_reviews'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], name=op.f('fk_follow_ups_session_id_screening_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow_ups'))
    )
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_ups_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_local_id'), ['local_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_follow_ups_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_ups_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_ups_status'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_session_id'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_patient_id'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_local_id'))
        batch_op.drop_index(batch_op.f('ix_follow_ups_due_date'))

    op.drop_table('follow_ups')
    with op.batch_alter_table('clinical_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_reviews_status'))
        batch_op.drop_index(batch_op.f('ix_clinical_reviews_session_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_reviews_reviewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_reviews_patient_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_reviews_local_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_reviews_decision'))

    op.drop_table('clinical_reviews')
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_to_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_status'))
        batch_op.drop_index(batch_op.f('ix_referrals_session_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_priority'))
        batch_op.drop_index(batch_op.f('ix_referrals_patient_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_local_id'))
        batch_op.drop_index(batch_op.f('ix_referrals_assigned_doctor_id'))

    op.drop_table('referrals')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_session_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_risk_level'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_requires_clinician_review'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_priority'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_explanations_session_id'))
        batch_op.drop_index(batch_op.f('ix_explanations_inference_result_id'))

    op.drop_table('explanations')
    with op.batch_alter_table('quality_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_assessments_session_id'))
        batch_op.drop_index(batch_op.f('ix_quality_assessments_result'))
        batch_op.drop_index(batch_op.f('ix_quality_assessments_is_acceptable'))
        batch_op.drop_index(batch_op.f('ix_quality_assessments_image_id'))

    op.drop_table('quality_assessments')
    with op.batch_alter_table('inference_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inference_results_status'))
        batch_op.drop_index(batch_op.f('ix_inference_results_session_id'))
        batch_op.drop_index(batch_op.f('ix_inference_results_local_id'))
        batch_op.drop_index(batch_op.f('ix_inference_results_is_development_model'))
        batch_op.drop_index(batch_op.f('ix_inference_results_image_id'))
        batch_op.drop_index(batch_op.f('ix_inference_results_category'))

    op.drop_table('inference_results')
    with op.batch_alter_table('retinal_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retinal_images_session_id'))
        batch_op.drop_index(batch_op.f('ix_retinal_images_patient_id'))
        batch_op.drop_index(batch_op.f('ix_retinal_images_local_id'))
        batch_op.drop_index(batch_op.f('ix_retinal_images_eye_side'))
        batch_op.drop_index(batch_op.f('ix_retinal_images_checksum'))

    op.drop_table('retinal_images')
    with op.batch_alter_table('screening_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screening_sessions_sync_status'))
        batch_op.drop_index(batch_op.f('ix_screening_sessions_state'))
        batch_op.drop_index(batch_op.f('ix_screening_sessions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_screening_sessions_local_id'))
        batch_op.drop_index(batch_op.f('ix_screening_sessions_conducted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_screening_sessions_clinic_id'))

    op.drop_table('screening_sessions')
    with op.batch_alter_table('patient_consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_consents_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_consents_consent_type'))

    op.drop_table('patient_consents')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('system_configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configuration_key'))
        batch_op.drop_index(batch_op.f('ix_system_configuration_category'))

    op.drop_table('system_configuration')
    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_queue_submitted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_sync_queue_status'))
        batch_op.drop_index(batch_op.f('ix_sync_queue_local_id'))
        batch_op.drop_index(batch_op.f('ix_sync_queue_entity_type'))
        batch_op.drop_index(batch_op.f('ix_sync_queue_device_id'))

    op.drop_table('sync_queue')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_portal_user_id'))
        batch_op.drop_index(batch_op.f('ix_patients_patient_code'))
        batch_op.drop_index(batch_op.f('ix_patients_clinic_id'))

    op.drop_table('patients')
    with op.batch_alter_table('model_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_metadata_version'))
        batch_op.drop_index(batch_op.f('ix_model_metadata_validation_status'))
        batch_op.drop_index(batch_op.f('ix_model_metadata_status'))
        batch_op.drop_index(batch_op.f('ix_model_metadata_name'))

    op.drop_table('model_metadata')
    with op.batch_alter_table('health_workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_workers_user_id'))
        batch_op.drop_index(batch_op.f('ix_health_workers_clinic_id'))

    op.drop_table('health_workers')
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_flags_key'))

    op.drop_table('feature_flags')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_user_id'))
        batch_op.drop_index(batch_op.f('ix_doctors_clinic_id'))

    op.drop_table('doctors')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_result'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_role'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinics_status'))
        batch_op.drop_index(batch_op.f('ix_clinics_name'))
        batch_op.drop_index(batch_op.f('ix_clinics_code'))

    op.drop_table('clinics')
    # ### end Alembic commands ###
